export function createCjsBinding(
  localName: string,
  pkgName: string,
  idents: string[],
  packageVersion?: string,
  compress = false,
): string {
  return `${bindingHeader}
${createCommonBinding(localName, pkgName, packageVersion, compress)}
module.exports = nativeBinding
${idents
  .map((ident) => `module.exports.${ident} = nativeBinding.${ident}`)
  .join('\n')}
`
}

export function createEsmBinding(
  localName: string,
  pkgName: string,
  idents: string[],
  packageVersion?: string,
  compress = false,
): string {
  return `${bindingHeader}
import { createRequire } from 'module'
const require = createRequire(import.meta.url)
const __dirname = new URL('.', import.meta.url).pathname

${createCommonBinding(localName, pkgName, packageVersion, compress)}
const { ${idents.join(', ')} } = nativeBinding
${idents.map((ident) => `export { ${ident} }`).join('\n')}
`
}

// Inlined zero-dependency loader for Brotli-compressed addons (`--compress`).
// Decompresses `<base>.node.br` (brotli) or `<base>.node.zst` (zstd) to a
// content-addressed cache on first load, picking the codec from the manifest,
// verifies sha256 before dlopen, then requires the real .node. A raw `<base>.node`
// next to the blob wins (dev / opt-out). Uses only built-ins available on the
// CLI's supported Node range (Brotli sync since 11.7); unprefixed requires keep
// the generated file parseable on the same range as the rest of this template.
// Exported for unit tests; embedded verbatim into the generated binding when
// `--compress` is set.
export const loadCompressedHelper = `function __napiLoadCompressed(dir, base) {
  const fs = require('fs')
  const path = require('path')
  const rawPath = path.join(dir, base + '.node')
  if (fs.existsSync(rawPath)) return require(rawPath)
  const manifestPath = path.join(dir, base + '.node.json')
  let manifest
  try {
    manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
  } catch (e) {
    throw new Error('napi-rs: cannot read the compression manifest for ' + base + ' at ' + manifestPath + ' (' + e.message + '). The compressed addon is missing files or corrupt; reinstall the package.')
  }
  const expected = manifest && manifest.sha256
  if (!expected) {
    throw new Error('napi-rs: compression manifest ' + manifestPath + ' has no sha256 field (saw ' + JSON.stringify(manifest) + '). Rebuild the addon with a current @napi-rs/cli.')
  }
  const isZstd = manifest.algo === 'zstd'
  const os = require('os')
  const cacheRoot = process.env.NAPI_RS_NATIVE_CACHE || process.env.XDG_CACHE_HOME || path.join(os.homedir() || os.tmpdir(), '.cache')
  const cacheDir = path.join(cacheRoot, 'napi-rs-native')
  const cacheFile = path.join(cacheDir, base + '-' + expected.slice(0, 16) + '.node')
  if (!fs.existsSync(cacheFile)) {
    const zlib = require('zlib')
    if (isZstd && typeof zlib.zstdDecompressSync !== 'function') {
      throw new Error('napi-rs: ' + base + ' is zstd-compressed and needs zstd in node:zlib (Node >= 22.15). Every maintained Node release (22 LTS, 24 LTS) includes it; this runtime is older/EOL. Upgrade Node (https://nodejs.org/en/about/previous-releases) or rebuild with the brotli codec.')
    }
    const blobPath = path.join(dir, base + (isZstd ? '.node.zst' : '.node.br'))
    let blob
    try {
      blob = fs.readFileSync(blobPath)
    } catch (e) {
      throw new Error('napi-rs: cannot read the compressed binary for ' + base + ' at ' + blobPath + ' (' + e.message + '). The compressed addon is missing files or corrupt; reinstall the package.')
    }
    const out = isZstd ? zlib.zstdDecompressSync(blob) : zlib.brotliDecompressSync(blob)
    const actual = require('crypto').createHash('sha256').update(out).digest('hex')
    if (actual !== expected) {
      throw new Error('napi-rs: integrity check failed for ' + base + ' at ' + blobPath + ' (saw sha256 ' + actual + ', wanted ' + expected + '). The binary is corrupt or tampered; reinstall the package.')
    }
    fs.mkdirSync(cacheDir, { recursive: true })
    const tmp = cacheFile + '.' + process.pid + '.tmp'
    fs.writeFileSync(tmp, out, { mode: 0o644 })
    fs.renameSync(tmp, cacheFile)
  }
  return require(cacheFile)
}
`

const bindingHeader = `// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */
`

function createCommonBinding(
  localName: string,
  pkgName: string,
  packageVersion?: string,
  compress = false,
): string {
  function requireTuple(tuple: string, identSize = 8) {
    const identLow = ' '.repeat(identSize - 2)
    const ident = ' '.repeat(identSize)
    // With `--compress`, the local .node and the platform package both ship a
    // `<base>.node.{br,zst}` + manifest instead of a raw .node; route both through the
    // self-extracting loader. Without it, emit the historical bare requires.
    const localLoad = compress
      ? `return __napiLoadCompressed(__dirname, '${localName}.${tuple}')`
      : `return require('./${localName}.${tuple}.node')`
    const pkgLoad = compress
      ? `return __napiLoadCompressed(require('path').dirname(require.resolve('${pkgName}-${tuple}/package.json')), '${localName}.${tuple}')`
      : `return require('${pkgName}-${tuple}')`
    const versionCheck = packageVersion
      ? `
${identLow}try {
${ident}const bindingPackageVersion = require('${pkgName}-${tuple}/package.json').version
${ident}if (bindingPackageVersion !== '${packageVersion}' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
${ident}  throw new Error(\`Native binding package version mismatch, expected ${packageVersion} but got \${bindingPackageVersion}. You can reinstall dependencies to fix this issue.\`)
${ident}}
${ident}${pkgLoad}
${identLow}} catch (e) {
${ident}loadErrors.push(e)
${identLow}}`
      : `
${identLow}try {
${ident}${pkgLoad}
${identLow}} catch (e) {
${ident}loadErrors.push(e)
${identLow}}`
    return `try {
${ident}${localLoad}
${identLow}} catch (e) {
${ident}loadErrors.push(e)
${identLow}}${versionCheck}`
  }

  return `const { readFileSync } = require('fs')
${compress ? loadCompressedHelper : ''}let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (process.report && typeof process.report.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      ${requireTuple('android-arm64')}
    } else if (process.arch === 'arm') {
      ${requireTuple('android-arm-eabi')}
    } else {
      loadErrors.push(new Error(\`Unsupported architecture on Android \${process.arch}\`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if ((process.config && process.config.variables && process.config.variables.shlib_suffix === 'dll.a') || (process.config && process.config.variables && process.config.variables.node_target_type === 'shared_library')) {
        ${requireTuple('win32-x64-gnu')}
      } else {
        ${requireTuple('win32-x64-msvc')}
      }
    } else if (process.arch === 'ia32') {
      ${requireTuple('win32-ia32-msvc')}
    } else if (process.arch === 'arm64') {
      ${requireTuple('win32-arm64-msvc')}
    } else {
      loadErrors.push(new Error(\`Unsupported architecture on Windows: \${process.arch}\`))
    }
  } else if (process.platform === 'darwin') {
    ${requireTuple('darwin-universal', 6)}
    if (process.arch === 'x64') {
      ${requireTuple('darwin-x64')}
    } else if (process.arch === 'arm64') {
      ${requireTuple('darwin-arm64')}
    } else {
      loadErrors.push(new Error(\`Unsupported architecture on macOS: \${process.arch}\`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      ${requireTuple('freebsd-x64')}
    } else if (process.arch === 'arm64') {
      ${requireTuple('freebsd-arm64')}
    } else {
      loadErrors.push(new Error(\`Unsupported architecture on FreeBSD: \${process.arch}\`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        ${requireTuple('linux-x64-musl', 10)}
      } else {
        ${requireTuple('linux-x64-gnu', 10)}
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        ${requireTuple('linux-arm64-musl', 10)}
      } else {
        ${requireTuple('linux-arm64-gnu', 10)}
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        ${requireTuple('linux-arm-musleabihf', 10)}
      } else {
        ${requireTuple('linux-arm-gnueabihf', 10)}
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        ${requireTuple('linux-loong64-musl', 10)}
      } else {
        ${requireTuple('linux-loong64-gnu', 10)}
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        ${requireTuple('linux-riscv64-musl', 10)}
      } else {
        ${requireTuple('linux-riscv64-gnu', 10)}
      }
    } else if (process.arch === 'ppc64') {
      ${requireTuple('linux-ppc64-gnu')}
    } else if (process.arch === 's390x') {
      ${requireTuple('linux-s390x-gnu')}
    } else {
      loadErrors.push(new Error(\`Unsupported architecture on Linux: \${process.arch}\`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      ${requireTuple('openharmony-arm64')}
    } else if (process.arch === 'x64') {
      ${requireTuple('openharmony-x64')}
    } else if (process.arch === 'arm') {
      ${requireTuple('openharmony-arm')}
    } else {
      loadErrors.push(new Error(\`Unsupported architecture on OpenHarmony: \${process.arch}\`))
    }
  } else {
    loadErrors.push(new Error(\`Unsupported OS: \${process.platform}, architecture: \${process.arch}\`))
  }
}

nativeBinding = requireNative()

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → force WASI fallback even if native loaded
//   'error'                  → force WASI and throw if no WASI binding is found
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a .wasi.cjs file.
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === 'true' || process.env.NAPI_RS_FORCE_WASI === 'error'

if (!nativeBinding || forceWasi) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./${localName}.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (forceWasi) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || forceWasi) {
    try {
      wasiBinding = require('${pkgName}-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (forceWasi) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      \`Cannot find native binding. \` +
        \`npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). \` +
        'Please try \`npm i\` again after removing both package-lock.json and node_modules directory.',
    )
    // assign instead of the \`new Error(message, { cause })\` options form,
    // which Node < 16.9 silently ignores
    error.cause = loadErrors.reduce((err, cur) => {
      cur.cause = err
      return cur
    })
    throw error
  }
  throw new Error(\`Failed to load native binding\`)
}
`
}
